### PR TITLE
added custom <a> styling to custom.scss

### PR DESCRIPTION
**Pull request by unimprobable**
Hi DarkXess,

I have added the custom <a> styling to the custom.scss file.

You'll see that it makes the links green, and pink when you hover over it.

You can go from here and change it to whatever colors you want.

Let me know if you have any questions.

Ni zhu zai Zhong guo ma?

Cheers,
Paul

### CODE REVIEW

**Comment by DarkXess** [comment]
haha you can speak Chinese? wow, I thought I was the only one who could be so fluent in Pinyin, many Chinese people say I am better than them as they often use characters instead of the pinyin itself. Shi, wo zai zhong guo, ting xihuan zai zhi li haha :)

About your commit, I have added it, the same result as I got on the localhost, but how to make the standard blue link as it is now red for example, hover over it isn't so important, just so that the links stand out more in the article :)

**Comment by unimprobable** [comment]
@DarkXess I am using Duolingo to learn Chinese. It works well! I don't know how to type characters on my pc though.

I don't see a red link, can you give me the page you see that on?

image

image

**Comment by DarkXess** [comment]
Hey, I mean the links as you see them reading the article, they are blue:

Screenshot_1

^as shown in the image. I would like that blue to be something more noticeable, such as red :)
Hover over is working yes, I just want to change the blue default to something so it's catching in the article haha.

If you want to learn Chinese, do you use WeChat? you can add me and I will gladly teach you what I know or help you when needed :)

**Comment by unimprobable** [comment]
Try to view your site in incognito, see if they are still blue.

This looks like they are blue because you have visited those links. This can be changed in a similar manner to how the hover is done. "Visited" is a pseudo class just like "hover".

image

Try to add a visited selector in the custom.scss file. You should nest it above the hover styling.

Checkout this tutorial and note about the order of pseudo classes about half way down the page. https://www.w3schools.com/css/css_pseudo_classes.asp

Thanks for the offer to add on WeChat, to tell the truth I don't have time for more Chinese lessons! I have a weekly tutor also.

**Comment by DarkXess** [comment]
Ahh okay, I get it now, well thanks so much for your help anyway - and good luck with your Chinese, feel free to contact me anytime if needed rpmoorey@gmail.com :)

**Comment by unimprobable** [comment]
No problem, let me know if you have any other questions. I've learned most of this stuff the hard way!

Cheers,
Paul
paul@unimprobable.com

**Pull request merged**
